"""Build the quick-launch page (launcher/index.html).

Notebook links point at a running Jupyter server, whose token changes on every
launch -- so this is regenerated by start.command each time rather than kept as
a static file.  The "current week" is computed in the browser at page load, so
the highlight stays correct without rebuilding.
"""

import datetime
import html
import json
import pathlib
import re
import subprocess
import sys
import urllib.parse

HERE = pathlib.Path(__file__).resolve().parent
COURSE = HERE.parent
BOOK = COURSE / "manipulation" / "book"
HANDOUTS = COURSE / "handouts"

TAG = re.compile(r"<[^>]+>")
WS = re.compile(r"\s+")


def clean(s):
    return WS.sub(" ", TAG.sub("", s)).strip()


CHNUM = re.compile(r"^(?:Ch\.|Chapter)\s*\d+\s*[-\u2013:]\s*", re.I)


def strip_num(s):
    """'Ch. 1 - Introduction' -> 'Introduction' (we render the number ourselves)."""
    return CHNUM.sub("", s).strip()


def chapter_title(cid):
    f = BOOK / f"{cid}.html"
    if not f.exists():
        return cid.replace("_", " ").title()
    src = f.read_text(errors="ignore")
    m = re.search(r"<title>(.*?)</title>", src, re.S)
    if m and clean(m.group(1)):
        return clean(m.group(1))
    m = re.search(r"<h1>(.*?)</h1>", src, re.S)
    return clean(m.group(1)) if m else cid.replace("_", " ").title()


def pretty(stem):
    s = stem.replace("_", " ").replace("-", " ")
    return s[:1].upper() + s[1:]


def discover_server():
    """Return (port, token) of a running Jupyter serving the book directory."""
    try:
        r = subprocess.run(
            ["jupyter", "lab", "list"], capture_output=True, text=True, timeout=20
        )
        out = (r.stdout or "") + (r.stderr or "")
    except Exception:
        return None, None
    for line in out.splitlines():
        if str(COURSE) in line or "manipulation/book" in line:
            m = re.search(r"http://localhost:(\d+)/\?token=(\w+)", line)
            if m:
                return m.group(1), m.group(2)
    return None, None


def collect_notebooks():
    """chapter id -> {'main': [...], 'exercises': [...]} of (label, relpath)."""
    found = {}
    for d in sorted(BOOK.iterdir()):
        if not d.is_dir() or d.name in ("htmlbook", "data"):
            continue
        main = sorted(p for p in d.glob("*.ipynb"))
        ex = sorted(p for p in d.glob("exercises/*.ipynb"))
        if main or ex:
            found[d.name] = {
                "main": [(pretty(p.stem), str(p.relative_to(BOOK))) for p in main],
                "exercises": [(pretty(p.stem), str(p.relative_to(BOOK))) for p in ex],
            }
    return found


# An exercise ends at </exercise>, the next <exercise>, or the end of the
# chapter body -- whichever comes first. Upstream occasionally leaves the last
# one unclosed (clutter.html's "Sampling Antipodal Grasps"); browsers tolerate
# that, and a strict <exercise>...</exercise> match would silently drop it.
EXERCISE = re.compile(
    r"<exercise([^>]*)>(.*?)(?=</exercise>|<exercise[\s>]|</chapter>|"
    r"<!-- EVERYTHING BELOW THIS LINE|\Z)", re.S)
# notebook_link('intro', notebook='exercises/02_x', link_text=...) -- the
# notebook argument is occasionally passed positionally.
NB_LINK = re.compile(r"notebook_link\(\s*'([^']+)'\s*,\s*(?:notebook\s*=\s*)?'([^']+)'")


def collect_exercises(order, num):
    """Chapter id -> exercises in textbook order, numbered as the book does
    (Exercise <chapter>.<k>). Read from the local book HTML; links only."""
    found = {}
    for cid in order:
        f = BOOK / f"{cid}.html"
        if not f.exists():
            continue
        src = f.read_text(errors="ignore")
        exs = []
        for k, m in enumerate(EXERCISE.finditer(src), 1):
            attrs, body = m.groups()
            ident = re.search(r'id="([^"]+)"', attrs)
            head = re.search(r"<h1>(.*?)</h1>", body, re.S)
            nbs = []
            for ch, nb in NB_LINK.findall(body):
                path = BOOK / ch / f"{nb}.ipynb"
                rel = str(path.relative_to(BOOK))
                if path.exists() and rel not in nbs:
                    nbs.append(rel)
            exs.append({
                "number": f"{num.get(cid, '?')}.{k}",
                "id": ident.group(1) if ident else None,
                "title": clean(head.group(1)) if head else f"Exercise {k}",
                "notebooks": nbs,
            })
        cited = {r for e in exs for r in e["notebooks"]}
        orphans = sorted(str(p.relative_to(BOOK)) for p in (BOOK / cid).glob("exercises/*.ipynb")
                         if str(p.relative_to(BOOK)) not in cited)
        if exs or orphans:
            found[cid] = exs
            if orphans:
                found.setdefault("_orphans", {})[cid] = orphans
    return found


def collect_psets():
    """Pset number -> its handout files. Read-only: we only ever link to these."""
    found = {}
    if not HANDOUTS.is_dir():
        return found
    for d in sorted(HANDOUTS.iterdir()):
        m = re.fullmatch(r"ps(\d+)", d.name) if d.is_dir() else None
        if not m:
            continue
        found[int(m.group(1))] = {
            "dir": d,
            "pdf": sorted(d.glob("*.pdf")),
            "code": sorted(d.glob("*.py")),
            "nb": sorted(d.glob("*.ipynb")),
        }
    return found


def main():
    port = token = None
    for arg in sys.argv[1:]:
        if arg.startswith("--port="):
            port = arg.split("=", 1)[1]
        elif arg.startswith("--token="):
            token = arg.split("=", 1)[1]
    if not port or not token:
        port, token = discover_server()

    schedule = json.loads((HERE / "schedule.json").read_text())
    psets = collect_psets()
    order = json.loads((BOOK / "chapters.json").read_text())["chapter_ids"]
    notebooks = collect_notebooks()
    titles = {cid: strip_num(chapter_title(cid)) for cid in notebooks}

    # chapter id -> ordinal, for display ("Ch. 3")
    num = {cid: i + 1 for i, cid in enumerate(order)}
    exercises = collect_exercises(order, num)
    orphan_nbs = exercises.pop("_orphans", {})
    for cid in exercises:
        titles.setdefault(cid, strip_num(chapter_title(cid)))
    # exercise notebook path -> "1.2 Drake Systems Fundamentals", so chips can
    # carry the textbook's own name instead of a prettified file name
    ex_label = {rel: f'{e["number"]} {e["title"]}'
                for exs in exercises.values() for e in exs for rel in e["notebooks"]}

    def ex_jump(cid):
        n = len(exercises.get(cid, []))
        if not n:
            return ""
        return (f'<a class="chip exjump" href="#ex-{cid}" data-ch="{cid}">'
                f'Ch. {num.get(cid, "?")} exercises ({n})</a>')

    base = f"http://localhost:{port}/lab/tree" if port else ""
    suffix = f"?token={token}" if token else ""

    def nb_link(label, rel):
        """A chip carrying both targets; the page's toggle picks which is live."""
        cur = "cursor://file" + urllib.parse.quote(str(BOOK / rel))
        # Server root is the course folder, so notebook paths are prefixed.
        jup = f"{base}/manipulation/book/{rel}{suffix}" if base else ""
        return (f'<a class="chip nb" data-j="{jup}" data-c="{cur}" '
                f'href="{jup or cur}">{html.escape(label)}</a>')

    # ---------- weeks ----------
    DAYNAME = ["Mon", "Tue", "Wed", "Thu", "Fri"]
    due_by_no = {}
    for dl in schedule.get("deadlines", []):
        m = re.match(r"Problem Set (\d+)", dl.get("label") or "")
        if m:
            due_by_no[int(m.group(1))] = dl["date"]

    def fmt(iso):
        return datetime.date.fromisoformat(iso).strftime("%a %b %-d")

    def cursor_url(path):
        return "cursor://file" + urllib.parse.quote(str(path))

    def pset_chips(n):
        """Links to a pset's handout files. Pset code is .py you edit, so these
        open in Cursor; the PDF opens in the browser/Preview."""
        ps = psets.get(n)
        if not ps:
            return ""
        # Open the repo ROOT as the workspace, not psN/ -- the root is what
        # carries utils/ (which pset code imports) and .vscode/settings.json
        # (which selects the right interpreter). With that window open, the
        # per-file chips below then open inside it.
        # windowId=_blank forces a new window. Without it Cursor only opens a
        # new window when none are open; otherwise the folder is routed into
        # whatever window is already up and the workspace never appears.
        bits = [f'<a class="chip work" href="{cursor_url(HANDOUTS)}?windowId=_blank" '
                f'title="Open the handouts repo as a Cursor workspace '
                f'(gives you utils/ and the right interpreter)">open workspace</a>']
        for f in ps["pdf"]:
            # Served over http by Jupyter when it is running: a file:// link is
            # blocked by browsers when clicked from a page, which kills the tab.
            rel = urllib.parse.quote(str(f.relative_to(COURSE)))
            href = (f"http://localhost:{port}/files/{rel}{suffix}" if port
                    else "file://" + urllib.parse.quote(str(f)))
            bits.append(f'<a class="chip pdf" target="_blank" rel="noopener" '
                        f'href="{href}">{html.escape(f.name)}</a>')
        for f in ps["code"] + ps["nb"]:
            bits.append(f'<a class="chip code" href="{cursor_url(f)}">'
                        f'{html.escape(f.name)}</a>')
        return f'<div class="links">{"".join(bits)}</div>' 
    weeks_html = []
    for i, w in enumerate(schedule["weeks"], 1):
        start = datetime.date.fromisoformat(w["start"])
        end = start + datetime.timedelta(days=4)
        rows = []
        for day in w["days"]:
            d = datetime.date.fromisoformat(day["date"])
            items = []
            lec = day["lecture"]
            if lec:
                chips = "".join(
                    f'<a class="chip ch" target="_blank" '
                    f'href="https://manipulation.mit.edu/{c}.html">Ch. {num.get(c, "?")} notes</a>'
                    for c in lec["chapters"]
                )
                nbs = "".join(
                    nb_link(lbl, rel)
                    for c in lec["chapters"]
                    for lbl, rel in notebooks.get(c, {}).get("main", [])
                ) + "".join(ex_jump(c) for c in lec["chapters"])
                items.append(
                    f'<div class="item lecture"><b>Lecture {lec["number"]}</b> '
                    f'{html.escape(lec["title"])}'
                    + (f'<div class="links">{chips}{nbs}</div>' if (chips or nbs) else "")
                    + "</div>"
                )
            for e in day["events"]:
                t = e["type"]
                label = e.get("label", "")
                cls = {"assignment": "pset", "quiz": "quiz", "deadline": "due",
                       "holiday": "off", "nolecture": "off", "norecitation": "off",
                       "institute": "inst", "recitation": "rec",
                       "assignment_out": "psetout"}.get(t, "misc")
                if t == "assignment":
                    tail = (f' <span class="note">out {fmt(e["out"])}</span>'
                            if e.get("out") else "")
                    items.append(
                        f'<div class="item {cls}"><b>{html.escape(label)} due</b> '
                        f'{html.escape(e["description"])}{tail}'
                        f'{pset_chips(e.get("number"))}</div>')
                elif t == "assignment_out":
                    due = due_by_no.get(e.get("number"))
                    tail = (f' <span class="note">\u00b7 due {fmt(due)}</span>'
                            if due else "")
                    items.append(
                        f'<div class="item {cls}"><b>{html.escape(label)}</b> '
                        f'handed out{tail}{pset_chips(e.get("number"))}</div>')
                else:
                    head = f"<b>{html.escape(label)}</b> " if label else ""
                    items.append(
                        f'<div class="item {cls}">{head}{html.escape(e["description"])}</div>')
            if items:
                rows.append(
                    f'<div class="day"><div class="dayname">{DAYNAME[d.weekday()]} '
                    f'{d.strftime("%b %-d")}</div><div class="items">'
                    + "".join(items) + "</div></div>"
                )
        weeks_html.append(
            f'<section class="week" data-start="{start}" data-end="{end}" id="w{i}">'
            f'<header><span class="wnum">Week {i}</span>'
            f'<span class="wdate">{start.strftime("%b %-d")} – {end.strftime("%b %-d")}</span>'
            f'<span class="badge">This week</span></header>'
            + ("".join(rows) or '<div class="empty">No scheduled items.</div>')
            + "</section>"
        )

    # ---------- chapters ----------
    chap_html = []
    for cid in order:
        if cid not in notebooks:
            continue
        nb = notebooks[cid]
        main = "".join(nb_link(l, r) for l, r in nb["main"])
        ex = "".join(nb_link(ex_label.get(r, l), r) for l, r in nb["exercises"])
        chap_html.append(
            f'<section class="chapter"><header><span class="cnum">Ch. {num[cid]}</span>'
            f'<h3>{html.escape(titles[cid])}</h3>'
            f'<a class="notes" target="_blank" href="https://manipulation.mit.edu/{cid}.html">notes ↗</a>'
            f'</header>'
            + (f'<div class="links">{main}</div>' if main else "")
            + (f'<div class="sub">Exercise notebooks</div><div class="links">{ex}{ex_jump(cid)}</div>'
               if ex else (f'<div class="links">{ex_jump(cid)}</div>' if ex_jump(cid) else ""))
            + "</section>"
        )
    # chapters with notebooks but not in the ordered list (template, figures, drafts)
    extra = [c for c in notebooks if c not in order]
    for cid in sorted(extra):
        nb = notebooks[cid]
        links = "".join(nb_link(l, r) for l, r in nb["main"] + nb["exercises"])
        chap_html.append(
            f'<section class="chapter other"><header><span class="cnum">–</span>'
            f'<h3>{html.escape(titles[cid])}</h3></header>'
            f'<div class="links">{links}</div></section>'
        )

    # ---------- exercises ----------
    ex_html = []
    for cid in order:
        exs = exercises.get(cid)
        if not exs and not orphan_nbs.get(cid):
            continue
        exs = exs or []
        with_nb = [e for e in exs if e["notebooks"]]
        written = [e for e in exs if not e["notebooks"]]

        def row(e):
            anchor = f'#{e["id"]}' if e["id"] else ""
            notes = (f'<a class="exnotes" target="_blank" '
                     f'href="https://manipulation.mit.edu/{cid}.html{anchor}">in notes \u2197</a>')
            def nb_label(r):
                if len(e["notebooks"]) == 1:
                    return "open notebook"
                ch = r.split("/", 1)[0]
                stem = pretty(pathlib.Path(r).stem)
                # say so when an exercise leans on another chapter's notebook
                return stem if ch == cid else f"{stem} (Ch. {num.get(ch, '?')})"
            chips = "".join(nb_link(nb_label(r), r) for r in e["notebooks"])
            return (f'<div class="ex"><span class="exn">{e["number"]}</span>'
                    f'<span class="ext">{html.escape(e["title"])}</span>'
                    f'<span class="exa">{chips}{notes}</span></div>')

        groups = ""
        if with_nb:
            groups += '<div class="sub">Notebook exercises</div>' + "".join(row(e) for e in with_nb)
        if written:
            groups += ('<div class="sub">Written / reading exercises</div>'
                       + "".join(row(e) for e in written))
        if orphan_nbs.get(cid):
            groups += ('<div class="sub">Other exercise notebooks '
                       '<span class="note">(in the repo, not cited by an exercise in the reading)</span></div>'
                       + "".join(f'<div class="ex"><span class="exn">\u2013</span>'
                                 f'<span class="ext">{html.escape(pretty(pathlib.Path(r).stem))}</span>'
                                 f'<span class="exa">{nb_link("open notebook", r)}</span></div>'
                                 for r in orphan_nbs[cid]))
        ex_html.append(
            f'<section class="chapter exch" id="ex-{cid}"><header>'
            f'<span class="cnum">Ch. {num[cid]}</span><h3>{html.escape(titles[cid])}</h3>'
            f'<span class="note">{len(exs)} exercises \u00b7 {len(with_nb)} with notebooks</span>'
            f'</header>{groups}</section>')

    # ---------- deadlines ----------
    dl_rows = []
    for dl in schedule.get("deadlines", []):
        d = datetime.date.fromisoformat(dl["date"])
        kind = {"assignment": "pset", "quiz": "quiz", "deadline": "due"}.get(
            dl["type"], "misc")
        name = dl["label"] or ("Quiz" if dl["type"] == "quiz" else "Deadline")
        out = (f'<span class="note">out {fmt(dl["out"])}</span>'
               if dl.get("out") else "")
        m = re.match(r"Problem Set (\d+)", name)
        mats = pset_chips(int(m.group(1))) if m else ""
        dl_rows.append(
            f'<div class="dl {kind}" data-date="{dl["date"]}">'
            f'<span class="dl-date">{d.strftime("%a %b %-d")}</span>'
            f'<span class="dl-name">{html.escape(name)}</span>'
            f'<span class="dl-desc">{html.escape(dl["description"])} {out}{mats}</span>'
            f'<span class="dl-when"></span></div>')
    deadlines_html = ('<section class="chapter"><header><h3>All due dates</h3>'
                      '<a class="notes" target="_blank" href="{{HANDOUTS}}">handouts repo \u2197</a>'
                      '</header>' + "".join(dl_rows) + "</section>")

    total = sum(len(v["main"]) + len(v["exercises"]) for v in notebooks.values())
    server_line = (
        f'<a href="http://localhost:{port}/lab{suffix}" target="_blank">localhost:{port}</a>'
        if port else '<span class="warn">Jupyter is not running — use start.command</span>'
    )

    tpl = (HERE / "template.html").read_text()
    out = (tpl
           .replace("{{WEEKS}}", "\n".join(weeks_html))
           .replace("{{CHAPTERS}}", "\n".join(chap_html))
           .replace("{{DEADLINES}}", deadlines_html)
           .replace("{{EXERCISES}}", "\n".join(ex_html))
           .replace("{{SERVER}}", server_line)
           .replace("{{TOTAL}}", str(total))
           .replace("{{HANDOUTS}}", schedule.get("handouts_repo") or "")
           .replace("{{GENERATED}}", datetime.datetime.now().strftime("%b %-d, %-I:%M %p")))
    (HERE / "index.html").write_text(out)
    print(f"built {HERE/'index.html'}  ({total} notebooks, "
          f"{len(psets)} pset{'' if len(psets) == 1 else 's'}, "
          f"{sum(map(len, exercises.values()))} exercises, "
          f"{'server ' + str(port) if port else 'no server'})")


if __name__ == "__main__":
    main()
