"""Build the quick-launch page (launcher/index.html).

Notebook links point at a running Jupyter server, whose token changes on every
launch -- so this is regenerated by start.command each time rather than kept as
a static file.  The "current week" is computed in the browser at page load, so
the highlight stays correct without rebuilding.
"""

import datetime
import html
import json
import pathlib
import re
import subprocess
import sys
import urllib.parse

HERE = pathlib.Path(__file__).resolve().parent
COURSE = HERE.parent
BOOK = COURSE / "manipulation" / "book"

TAG = re.compile(r"<[^>]+>")
WS = re.compile(r"\s+")


def clean(s):
    return WS.sub(" ", TAG.sub("", s)).strip()


CHNUM = re.compile(r"^(?:Ch\.|Chapter)\s*\d+\s*[-\u2013:]\s*", re.I)


def strip_num(s):
    """'Ch. 1 - Introduction' -> 'Introduction' (we render the number ourselves)."""
    return CHNUM.sub("", s).strip()


def chapter_title(cid):
    f = BOOK / f"{cid}.html"
    if not f.exists():
        return cid.replace("_", " ").title()
    src = f.read_text(errors="ignore")
    m = re.search(r"<title>(.*?)</title>", src, re.S)
    if m and clean(m.group(1)):
        return clean(m.group(1))
    m = re.search(r"<h1>(.*?)</h1>", src, re.S)
    return clean(m.group(1)) if m else cid.replace("_", " ").title()


def pretty(stem):
    s = stem.replace("_", " ").replace("-", " ")
    return s[:1].upper() + s[1:]


def discover_server():
    """Return (port, token) of a running Jupyter serving the book directory."""
    try:
        r = subprocess.run(
            ["jupyter", "lab", "list"], capture_output=True, text=True, timeout=20
        )
        out = (r.stdout or "") + (r.stderr or "")
    except Exception:
        return None, None
    for line in out.splitlines():
        if "manipulation/book" in line or str(BOOK) in line:
            m = re.search(r"http://localhost:(\d+)/\?token=(\w+)", line)
            if m:
                return m.group(1), m.group(2)
    return None, None


def collect_notebooks():
    """chapter id -> {'main': [...], 'exercises': [...]} of (label, relpath)."""
    found = {}
    for d in sorted(BOOK.iterdir()):
        if not d.is_dir() or d.name in ("htmlbook", "data"):
            continue
        main = sorted(p for p in d.glob("*.ipynb"))
        ex = sorted(p for p in d.glob("exercises/*.ipynb"))
        if main or ex:
            found[d.name] = {
                "main": [(pretty(p.stem), str(p.relative_to(BOOK))) for p in main],
                "exercises": [(pretty(p.stem), str(p.relative_to(BOOK))) for p in ex],
            }
    return found


def main():
    port = token = None
    for arg in sys.argv[1:]:
        if arg.startswith("--port="):
            port = arg.split("=", 1)[1]
        elif arg.startswith("--token="):
            token = arg.split("=", 1)[1]
    if not port or not token:
        port, token = discover_server()

    schedule = json.loads((HERE / "schedule.json").read_text())
    order = json.loads((BOOK / "chapters.json").read_text())["chapter_ids"]
    notebooks = collect_notebooks()
    titles = {cid: strip_num(chapter_title(cid)) for cid in notebooks}

    # chapter id -> ordinal, for display ("Ch. 3")
    num = {cid: i + 1 for i, cid in enumerate(order)}

    base = f"http://localhost:{port}/lab/tree" if port else ""
    suffix = f"?token={token}" if token else ""

    def nb_link(label, rel):
        """A chip carrying both targets; the page's toggle picks which is live."""
        cur = "cursor://file" + urllib.parse.quote(str(BOOK / rel))
        jup = f"{base}/{rel}{suffix}" if base else ""
        return (f'<a class="chip nb" data-j="{jup}" data-c="{cur}" '
                f'href="{jup or cur}">{html.escape(label)}</a>')

    # ---------- weeks ----------
    DAYNAME = ["Mon", "Tue", "Wed", "Thu", "Fri"]
    due_by_no = {}
    for dl in schedule.get("deadlines", []):
        m = re.match(r"Problem Set (\d+)", dl.get("label") or "")
        if m:
            due_by_no[int(m.group(1))] = dl["date"]

    def fmt(iso):
        return datetime.date.fromisoformat(iso).strftime("%a %b %-d")
    weeks_html = []
    for i, w in enumerate(schedule["weeks"], 1):
        start = datetime.date.fromisoformat(w["start"])
        end = start + datetime.timedelta(days=4)
        rows = []
        for day in w["days"]:
            d = datetime.date.fromisoformat(day["date"])
            items = []
            lec = day["lecture"]
            if lec:
                chips = "".join(
                    f'<a class="chip ch" target="_blank" '
                    f'href="https://manipulation.mit.edu/{c}.html">Ch. {num.get(c, "?")} notes</a>'
                    for c in lec["chapters"]
                )
                nbs = "".join(
                    nb_link(lbl, rel)
                    for c in lec["chapters"]
                    for lbl, rel in notebooks.get(c, {}).get("main", [])
                )
                items.append(
                    f'<div class="item lecture"><b>Lecture {lec["number"]}</b> '
                    f'{html.escape(lec["title"])}'
                    + (f'<div class="links">{chips}{nbs}</div>' if (chips or nbs) else "")
                    + "</div>"
                )
            for e in day["events"]:
                t = e["type"]
                label = e.get("label", "")
                cls = {"assignment": "pset", "quiz": "quiz", "deadline": "due",
                       "holiday": "off", "nolecture": "off", "norecitation": "off",
                       "institute": "inst", "recitation": "rec",
                       "assignment_out": "psetout"}.get(t, "misc")
                if t == "assignment":
                    tail = (f' <span class="note">out {fmt(e["out"])}</span>'
                            if e.get("out") else "")
                    items.append(
                        f'<div class="item {cls}"><b>{html.escape(label)} due</b> '
                        f'{html.escape(e["description"])}{tail}</div>')
                elif t == "assignment_out":
                    due = due_by_no.get(e.get("number"))
                    tail = (f' <span class="note">\u00b7 due {fmt(due)}</span>'
                            if due else "")
                    items.append(
                        f'<div class="item {cls}"><b>{html.escape(label)}</b> '
                        f'handed out{tail}</div>')
                else:
                    head = f"<b>{html.escape(label)}</b> " if label else ""
                    items.append(
                        f'<div class="item {cls}">{head}{html.escape(e["description"])}</div>')
            if items:
                rows.append(
                    f'<div class="day"><div class="dayname">{DAYNAME[d.weekday()]} '
                    f'{d.strftime("%b %-d")}</div><div class="items">'
                    + "".join(items) + "</div></div>"
                )
        weeks_html.append(
            f'<section class="week" data-start="{start}" data-end="{end}" id="w{i}">'
            f'<header><span class="wnum">Week {i}</span>'
            f'<span class="wdate">{start.strftime("%b %-d")} – {end.strftime("%b %-d")}</span>'
            f'<span class="badge">This week</span></header>'
            + ("".join(rows) or '<div class="empty">No scheduled items.</div>')
            + "</section>"
        )

    # ---------- chapters ----------
    chap_html = []
    for cid in order:
        if cid not in notebooks:
            continue
        nb = notebooks[cid]
        main = "".join(nb_link(l, r) for l, r in nb["main"])
        ex = "".join(nb_link(l, r) for l, r in nb["exercises"])
        chap_html.append(
            f'<section class="chapter"><header><span class="cnum">Ch. {num[cid]}</span>'
            f'<h3>{html.escape(titles[cid])}</h3>'
            f'<a class="notes" target="_blank" href="https://manipulation.mit.edu/{cid}.html">notes ↗</a>'
            f'</header>'
            + (f'<div class="links">{main}</div>' if main else "")
            + (f'<div class="sub">Exercises / psets</div><div class="links">{ex}</div>' if ex else "")
            + "</section>"
        )
    # chapters with notebooks but not in the ordered list (template, figures, drafts)
    extra = [c for c in notebooks if c not in order]
    for cid in sorted(extra):
        nb = notebooks[cid]
        links = "".join(nb_link(l, r) for l, r in nb["main"] + nb["exercises"])
        chap_html.append(
            f'<section class="chapter other"><header><span class="cnum">–</span>'
            f'<h3>{html.escape(titles[cid])}</h3></header>'
            f'<div class="links">{links}</div></section>'
        )

    # ---------- deadlines ----------
    dl_rows = []
    for dl in schedule.get("deadlines", []):
        d = datetime.date.fromisoformat(dl["date"])
        kind = {"assignment": "pset", "quiz": "quiz", "deadline": "due"}.get(
            dl["type"], "misc")
        name = dl["label"] or ("Quiz" if dl["type"] == "quiz" else "Deadline")
        out = (f'<span class="note">out {fmt(dl["out"])}</span>'
               if dl.get("out") else "")
        dl_rows.append(
            f'<div class="dl {kind}" data-date="{dl["date"]}">'
            f'<span class="dl-date">{d.strftime("%a %b %-d")}</span>'
            f'<span class="dl-name">{html.escape(name)}</span>'
            f'<span class="dl-desc">{html.escape(dl["description"])} {out}</span>'
            f'<span class="dl-when"></span></div>')
    deadlines_html = ('<section class="chapter"><header><h3>All due dates</h3>'
                      '<a class="notes" target="_blank" href="{{HANDOUTS}}">handouts repo \u2197</a>'
                      '</header>' + "".join(dl_rows) + "</section>")

    total = sum(len(v["main"]) + len(v["exercises"]) for v in notebooks.values())
    server_line = (
        f'<a href="http://localhost:{port}/lab{suffix}" target="_blank">localhost:{port}</a>'
        if port else '<span class="warn">Jupyter is not running — use start.command</span>'
    )

    tpl = (HERE / "template.html").read_text()
    out = (tpl
           .replace("{{WEEKS}}", "\n".join(weeks_html))
           .replace("{{CHAPTERS}}", "\n".join(chap_html))
           .replace("{{DEADLINES}}", deadlines_html)
           .replace("{{SERVER}}", server_line)
           .replace("{{TOTAL}}", str(total))
           .replace("{{HANDOUTS}}", schedule.get("handouts_repo") or "")
           .replace("{{GENERATED}}", datetime.datetime.now().strftime("%b %-d, %-I:%M %p")))
    (HERE / "index.html").write_text(out)
    print(f"built {HERE/'index.html'}  ({total} notebooks, "
          f"{'server ' + str(port) if port else 'no server'})")


if __name__ == "__main__":
    main()
